name: Update
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge upstream
        run: |
          git config --global user.name 'Pipeline'
          git config --global user.email 'info@bodyassist.app'

          git remote add upstream https://github.com/tobiasbenkner/app.bodyassist.app.git
          git fetch upstream

          git checkout gh-pages
          git merge -X theirs --allow-unrelated-histories --no-commit upstream/gh-pages
          echo ${{ github.event.repository.name }} > CNAME

          if [ -n "$(git status --porcelain)" ]; then
            git add .;
            git commit -m "update fork";
            git push;
          else
            echo "no changes";
          fi
